apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - destination-rule.yaml
  - proclone-backend-deployment.yaml
  - proclone-backend-svc.yaml
  - proxmox-service-entry.yaml
  - service-entry.yaml
